repository: ocp-tests
variants:
 - name: openshift-container-platform
   attributes:
    - _attributes/ocp-attributes.adoc
   build: true
   files:
     included:
       - openshift_images/**/*.adoc
       - modules/**/*.adoc      
       - images/*.png
       - images/*.svg
     excluded:
       - contributing_to_docs/**/*.adoc
       - mod_docs_guide/**/*.adoc
       - rosa_architecture/**/*.adoc
       - rosa_planning/**/*.adoc
       - rosa_getting_started_sts/**/*.adoc
       - rosa_getting_started/**/*.adoc
       - adding_service_cluster/**/*.adoc
       - rosa_cli/**/*.adoc
       - cloud_infrastructure_access/**/*.adoc
       - rosa_policy/**/*.adoc
       - rosa_support/**/*.adoc
       - osd_architecture/**/*.adoc
       - osd_planning/**/*.adoc
       - osd_quickstart/**/*.adoc
       - administering_a_cluster/**/*.adoc
       - osd_cluster_create/**/*.adoc
       - upgrading/**/*.adoc
       - osd_notifications/**/*.adoc
       - osd_policy/**/*.adoc
       - _unused_topics/**/*.adoc
       - _package/**/*.*
       - _stylesheets/**/*.*
       - scripts/**/*.*
       - _images/**/*.*
       - _javascript/**/*.*
       - _preview/**/*.*
       - _snippets/**/*.*
       - _templates/**/*.*
       - _topic_maps/**/*.*
       - .github/**/*.*
       - .git/**/*.*
       - .s2i/**/*.*
 - name: openshift-dedicated
   attributes:
    - _attributes/osd-attributes.adoc
   build: false
   files:
     included:
       - osd_architecture/**/*.adoc
       - welcome/**/*.adoc
       - osd_planning/**/*.adoc
       - osd_quickstart/**/*.adoc
       - osd_cluster_create/**/*.adoc
       - identity_providers/**/*.adoc
       - administering_a_cluster/**/*.adoc
       - upgrading/**/*.adoc
       - osd_notifications/**/*.adoc
       - adding_service/**/*.adoc
       - osd_private_connections/**/*.adoc
       - networking/openshift_sdn/**/*.adoc
       - nodes/**/*.adoc
       - monitoring/**/*.adoc
       - applications/deployments/**/*.adoc
       - osd_policy/**/*.adoc
       - support/**/*.adoc
       - modules/**/*.adoc
     excluded:
       - _unused_topics
       - _package
       - _stylesheets
       - scripts
       - installing
       - whats_new
       - _images
       - _javascript
       - _preview
       - _snippets
       - _templates
       - _topic_maps
       - .github
       - .git
       - .s2i
