:_content-type: ASSEMBLY
[id="microshift-understanding"]
= Understanding MicroShift
include::_attributes/attributes-microshift.adoc[]
:context: microshift-understanding
toc::[]

Learn about {product-title}, interacting with {product-title} the command-line interface (CLI) tools, consumption experience, and integration with {op-system-first}.

[id="microshift-understanding-about_{context}"]
== About MicroShift

MicroShift is a distribution of OpenShift Kubernetes optimized for small form factor and edge computing.

Edge devices deployed out in the field pose very different operational, environmental, and business challenges from those of cloud computing. These motivate different engineering trade-offs for Kubernetes at the far edge than for cloud or near-edge scenarios. MicroShift's design goals cater to this:

- make frugal use of system resources (CPU, memory, network, storage, etc.)
- tolerate severe networking constraints
- update securely, safely, quickly, and seamlessly (without disrupting workloads)
- build on and integrate cleanly with edge-optimized operating systems like Fedora IoT and {op-system-first}
- provide a consistent development and management experience with other distributions of OpenShift
